"""
Sequential job recommendation orchestrator using Microsoft Agent Framework.
Uses SequentialBuilder to create a pipeline of agents.
"""
import logging
from agent_framework import SequentialBuilder, WorkflowOutputEvent, ChatMessage
from agent_framework.azure import AzureOpenAIChatClient

from agents.job_extractor_agent import build_job_extractor_agent
from agents.job_recommender_agent import build_job_recommender_agent
from agents.job_summary_agent import build_job_summary_agent
from utils.result_formatter import format_staged_results

# Set up logging for structured workflow information
logger = logging.getLogger(__name__)


async def run_job_recommendation_AI_workflow(chat_client: AzureOpenAIChatClient, user_profile: str) -> str:
    """
    Run the sequential job recommendation workflow.
    
    Flow: Job Extractor -> Job Recommender -> Job Summarizer
    
    Args:
        chat_client: Azure OpenAI chat client
        user_profile: User's skills, experience, and job preferences
        
    Returns:
        Formatted output showing the complete conversation flow
    """
    
    logger.info("[WORKFLOW] Job recommendation workflow initialized")
    logger.info(f"[WORKFLOW] Starting job recommendation workflow")
    logger.info(f"[WORKFLOW] Profile: {user_profile}")
    
    # Build the three agents
    extractor = build_job_extractor_agent(chat_client)
    recommender = build_job_recommender_agent(chat_client)
    summarizer = build_job_summary_agent(chat_client)
    
    logger.info("[WORKFLOW] Created 3 agents: extractor -> recommender -> summarizer")
    
    # Build sequential workflow using SequentialBuilder
    workflow = (
        SequentialBuilder()
        .participants([extractor, recommender, summarizer])
        .build()
    )
    
    logger.info("[WORKFLOW] Sequential workflow built successfully")
    
    # Run the workflow and capture all messages
    all_messages = []
    
    async for event in workflow.run_stream(
        f"Search for jobs matching this user profile: {user_profile}"
    ):
        if isinstance(event, WorkflowOutputEvent):
            # WorkflowOutputEvent.data contains a list of messages
            if isinstance(event.data, list):
                all_messages.extend(event.data)
            else:
                all_messages.append(event.data)
    
    if not all_messages:
        return "ERROR: Workflow did not produce any output."
    
    logger.info(f"[WORKFLOW] Job recommendation workflow completed successfully")
    logger.info(f"[WORKFLOW] Total messages captured: {len(all_messages)}")
    
    # Process messages by stages and return structured results
    if all_messages:
        return format_staged_results(all_messages, user_profile)
    else:
        return "No results generated by the workflow."


